paths:
  faiss_index: "data/processed/faiss.index"
  docstore: "data/processed/docstore.json"
  source_csv: "structured_case_studies_final.csv"

models:
  embedding: "all-MiniLM-L6-v2"
  local_generator: "google/flan-t5-base"

rag:
  top_k: 4