import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ui/ClientLayout"; 
import { FloatingDock } from "../components/ui/floating-dock";
import { IconArrowUp, IconHistory, IconHome } from "@tabler/icons-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chispa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dockItems = [
    {
      title: "Home",
      icon: (
        <IconHome className="h-full w-full text-neutral-500 dark:text-neutral-300" />
      ),
      href: "/",
    },
    {
      title: "Input",
      icon: (
        <IconArrowUp className="h-full w-full text-neutral-500 dark:text-neutral-300" />
      ),
      href: "/input",
    },
    {
      title: "History",
      icon: (
        <IconHistory className="h-full w-full text-neutral-500 dark:text-neutral-300" />
      ),
      href: "/history",
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>
          {children}
          {/* Floating Dock */}
          <FloatingDock
            desktopClassName="fixed bottom-10 left-1/2 -translate-x-1/2 z-50"
            mobileClassName="fixed bottom-10 right-6 z-50"
            items={dockItems}
          />
        </ClientLayout>
      </body>
    </html>
  );
}